server:
  port: 8080

spring:
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: abr123
    url: jdbc:mysql://localhost:3306/blog_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml
